dist: precise
language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker

jobs: 
  include:
    install:
      - pushd contrib/read-properties
      - mvn -q install
      - popd
      - pushd contrib/assert-properties
      - mvn -q install
      - popd

    script:
      - travis_wait mvn -q -Pdev,dist install -DskipTests
      - mvn -Dsurefire.forkCount=4 -Pdev verify
      - contrib/datawave-quickstart/docker/docker-build.sh test-image --use-existing-binaries

